<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  0 => '',
  '<h4>Hello, {username}</h4>
								<p>Someone asked for password reset on {sitename}.</p>
								<p>If it was you, please follow this <a href="{url}">link</a> or use following verification key on password reset page:</p>
								<p><b>{key}</b></p>
								<br />
								<p>You received this letter because you are registered on <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>' => 
  '<h4>Здравствуйте, {username}</h4>
								<p>Кто-то запросил сброс пароля на {sitename}.</p>
								<p>Если это были вы, пожалуйста, перейдите по <a href="{url}">ссылке</a> или используйте этот код на странице сброса пароля:</p>
								<p><b>{key}</b></p>
								<br />
								<p>Вы получили это письмо потому что вы зарегистрированы на <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>',
  '<h4>Welcome to {site_name}</h4>' => '<h4>Добро пожаловать на {site_name}</h4>',
  'Add' => 'Добавить',
  'Add Category' => 'Добавить категорию',
  'Add content' => 'Добавить контент',
  'Add expense' => 'Учесть расходы',
  'Admin panel' => '',
  'Before adding reminders you should set car mileage.' => 'Прежде чем добавить напоминания, необходимо указать пробег автомоиля.',
  'Buy 1 year and save 20%' => 'Купить на 1 год со скидкой 20%',
  'Buy 6 months for just $6' => 'Купить на 6 месяцев за 6у.е.',
  'By expence type:' => 'По типу расходов',
  'Category' => 'Категория',
  'Change current' => 'Изменить текущее',
  'Clear unused categories' => 'Очистить неиспользуемые категории',
  'Cost' => 'Стоимость',
  'Currency' => 'Валюта',
  'Don\'t have account?' => 'Не зарегистрированы?',
  'Edit content' => 'Редактировать контент',
  'Expense' => 'Трата',
  'Expenses' => 'Расходы',
  'Expenses for: ' => 'Расходы для: ',
  'Forgot password?' => 'Забыли пароль?',
  'Get Premium' => 'Купить премиум-аккаунт',
  'Key is wrong.' => 'Код не верный.',
  'Login with' => 'Войти с помощью',
  'Manage coupons' => 'Управление купонами',
  'Name RU' => 'Имя по-русски',
  'Name Ru' => 'Имя по-русски',
  'New expense' => 'Новая трата',
  'New expense category' => 'Новая категория расходов',
  'Or enter promo-code' => 'Или введите промо-код',
  'Password reset key' => 'Код сброса пароля',
  'Primary' => 'Первичный',
  'Reset password' => 'Сбросить пароль',
  'Select goodie if needed' => '',
  'Shop and service stations' => 'Магазины и СТО',
  'Show All' => 'Показать всё',
  'Show charts' => 'Показать на графиках',
  'Submit' => 'Отправить',
  'The state does not match. You may be a victim of CSRF.' => '',
  'This promo-code has been already expired.' => 'Этот код уже истек.',
  'Time' => 'Время',
  'Title' => 'Название',
  'Uid' => '',
  'Update expense' => 'Изменить трату',
  'User with such email address is not registered.' => 'Пользователь с таким адресом email не зарегистрирован',
  'Verification key was sent, please check you email.' => 'Код подтверждения был отправлен на вааш электронный адрес. Пожалйуста, проверьте свой email.',
  'Welcome to Premium.' => 'Добро пожаловать в премиум-аккаунт',
  'Without premium account you cannot add your shop.' => 'Без премиум-аккаунта Вы не можете добавить магазин',
  'Wrong promo-code.' => 'Неверный промо-код',
  'Your car' => 'Ваш автомобиль',
  'Your expenses dynamic' => 'Динамика ваших расходов',
  'Your last login was: {datetime}' => 'Вы последний раз входили: {datetime}',
  'update' => 'обновить',
  'Manage shops' => '@@Управление магазинами@@',
  'New Update (uncheck to edit current)' => '@@Новое бновление (снимите галочку для редактирования текущего)@@',
  'Not registered?' => '@@Не зарегистрированы?@@',
  'This is simple service cron application for your car.' => '@@This is simple service cron application for your car@@',
  'Where to buy necessary parts' => '@@Где купить необходимые запчасти и услуги@@',
  'Your car: ' => '@@Ваша машина@@',
  '<h4>Hello, {username}</h4>
								<p>Your premium subscription expires in <b>{time_left} days</b></p>
								<p>After that you won\'t be able to access some feature like managing multiple cars and custom reminders, etc.</p>
								<br />
								<p>You can update it by following this <a href="{url}">link</a>.</p>
								<br />
								<p>You received this letter because you are registered on <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>' => '<h4>Здравствуйте, {username}</h4>
								<p>Ваша премиум-подписка истекает через <b>{time_left} дней</b></p>
								<p>После этого вы потеряете доступ к премиум-функциям (например, управление несколькими автомобилями, собственные типы уведомлений, и т.д.)</p>
								<br />
								<p>Вы можете продлить подписку, пройдя по этой <a href="{url}">ссылке</a>.</p>
								<br />
								<p>Вы получили это письмо потому что вы зарегистрированы на <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>',
  '<h4>Hello, {username}</h4>
								<p>Your premium subscription has been expired <b>{time_left} days ago</b></p>
								<p>Without it you are not able to access some feature like managing multiple cars and custom reminders, etc.</p>
								<br />
								<p>You can update it by following this <a href="{url}">link</a>.</p>
								<br />
								<p>You received this letter because you are registered on <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>' => '<h4>Здравствуйте, {username}</h4>
								<p>Ваша премиум-подписка истекла <b>{time_left} дней назад</b></p>
								<p>Без нее вы не имеете доступ к премиум-функциям (например, управление несколькими автомобилями, собственные типы уведомлений, и т.д.)</p>
								<br />
								<p>Вы можете продлить подписку, пройдя по этой <a href="{url}">ссылке</a>.</p>
								<br />
								<p>Вы получили это письмо потому что вы зарегистрированы на <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>',
  '<h4>Hello, {username}</h4>
						<p>We have to remind you about <b>{cron_name}</b></p>
						<p>It expires in: {expire_value} {expire_type}.</p>
						<br />
						<p>You can update it by following this <a href="{cron_url}">link</a>.</p>
						<br />
						<p>You received this letter because you are registered on <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>' => '<h4>Здравствуйте, {username}</h4>
						<p>Это напоминание о <b>{cron_name}</b></p>
						<p>Оно истекает через: {expire_value} {expire_type}.</p>
						<br />
						<p>Вы можете обновить его, пройдя по этой <a href="{cron_url}">ссылке</a>.</p>
						<br />
						<p>Вы получили это письмо потому что вы зарегистрированы на <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>',
  '<h4>Hello, {username}</h4>
						<p>Your car <b>{car_name}</b> is outdated:</p>
						<ul><li>{reminders}</li></ul>
						<br />
						<p>You can update it by following this <a href="{url}">link</a>.</p>
						<br />
						<p>You received this letter because you are registered on <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>' => '<h4>Здравствуйте, {username}</h4>
						<p>Информация о вашем автомобиле <b>{car_name}</b> устарела:</p>
						<ul><li>{reminders}</li></ul>
						<br />
						<p>Вы можете бновить ее, пройдя по этой <a href="{url}">ссылке</a>.</p>
						<br />
						<p>Вы получили это письмо потому что вы зарегистрированы на <a target="_blank" href="{siteurl}"><b>{sitename}</b></a></p>',
  '<p>To perform this action you need to get premium account.</p>' => '<p>Для этого действия вам необходим премиум-аккаунт.</p>',
  '<p>To update your current account to premium please follow these steps:</p>' => '<p>Чтобы повысить ваш аккаунт до уровня премиум, пожалуйста, следуйте инструкциям:</p>',
  'About' => 'О программе',
  'Active' => 'Активный',
  'Add car' => 'Добавить автомобиль',
  'Add car: ' => 'Добавить автомобиль:',
  'Add reminder' => 'Добавить напоминание',
  'Add reminder type' => 'Добавить тип напоминания',
  'Add service: ' => 'Добавить сервис',
  'Add services' => 'Добавить сервисы',
  'Add supported brand: ' => 'Добавить поддерживаемый бренд',
  'Add supported brands' => 'Добавить поддерживаемые бренды',
  'Address' => 'Адрес',
  'Agree with terms.' => 'Я согласен с условиями использования',
  'All Brands' => 'Все брэнды',
  'All brands' => 'Все брэнды',
  'Also, you are able to use application with all available user experience, in this case you can choose your car at this point too. Or you can ignore that and proceed with registration' => 'Также, вы можете при этом пользоваться приложением как пользователь, для этого вы можете выбрать свою машину на этом этапе. Или вы можете продолжить регистрацию без выбора автомобиля.',
  'Back' => 'Назад',
  'Brand' => 'Брэнд',
  'By registering seller account you become able to sell auto parts to other users. Once you share your location in profile settings, other members will see your proposals (you can select which parts type you are selling and for which auto brands).' => 'Регистрируя аккаунт продавца вы получаете возможность продавать запчасти и услуги другим пользователям. Как только вы добавите информацию о вашем магазине и его расположении, другие пользователи смогут видеть ваши предложения (вы можете выбрать типа предоставляемого сервиса и список поддерживаемых брэндов).',
  'Car' => 'Автомобиль',
  'Car model variant' => 'Вариант модели',
  'Car model version' => 'Версия модели',
  'Car name' => 'Название автомобиля',
  'Change location' => 'Изменить расположение',
  'Choose Variant' => 'Выберите вариант',
  'Choose Version' => 'Выбериет версию',
  'Choose another' => 'Изменить',
  'Choose car' => 'Выберите автомобиль',
  'Choose make' => 'Выберите производителя',
  'Choose model' => 'Выберите модель',
  'Choose type' => 'Выберите тип',
  'Coordinates' => 'Координаты',
  'Country' => 'Страна',
  'Create' => 'Создать',
  'Create Shop' => 'Добавить магазин',
  'Creator' => 'Создатель',
  'Cron Type' => 'Тип напоминания',
  'Current mileage' => 'Текущий километраж',
  'Date added' => 'Дата добавления',
  'Delete' => 'Удалить',
  'Delete Shop' => 'Удалить',
  'Delete car' => 'Удалить',
  'Description' => 'Описание',
  'Edit Shop' => 'Редактировать',
  'Edit reminder: ' => 'Обновить напоминание',
  'Email' => 'Email',
  'Go back' => 'Перейти назад',
  'Go to current location' => 'Перейти к текущим координатам',
  'Google search results' => 'Результаты поиска Google',
  'Hi, {username}' => 'Здравствуйте, {username}',
  'Home' => 'Главная',
  'I\'m a seller' => 'Я продавец',
  'Image' => 'Изображение',
  'In months' => 'В месяцах',
  'Incorrect email or password.' => 'Неверный email или пароль',
  'Initial mileage' => 'Начальный пробег',
  'Kilometers' => 'Километры',
  'Language' => 'Язык',
  'Last Login' => 'Последний логин',
  'Last Update' => 'Последнее обновление',
  'Last update' => 'Последнее обновление',
  'Learn more about location sharing' => 'Узнать больше о предоставлении координат',
  'Learn more about seller account' => 'Узнать больше об аккаунте продавца',
  'Location' => 'Расположение',
  'Login' => 'Войти',
  'Logout' => 'Выйти',
  'Manage Shop' => 'Управление магазинами',
  'Mileage' => 'Пробег',
  'Mileage is not set' => 'Пробег не указан',
  'Mileage is outdated' => 'Пробег устарел',
  'Miles' => 'Мили',
  'Miles/Kilometers' => 'Мили/километры',
  'Name' => 'Имя',
  'New reminder type: ' => 'Новый тип напоминания',
  'New reminder: ' => 'Новое напоминание',
  'No results found' => 'Ничего не найдено',
  'Only premium account users can add their own reminder types.' => 'Только пользователи премиум-аккаунта могут добавлять свои типы напоминаний.',
  'Password' => 'Пароль',
  'Password repeat' => 'Пароль повторно',
  'Passwords should match' => 'Пароли должны совпадать',
  'Period' => 'Период',
  'Phones' => 'Телефоны',
  'Please select your car' => 'Выберите ваш автомобиль',
  'Premium subscription expiration reminder' => 'Напоминание об истечении срока премиум-подписки',
  'Proceed' => 'Продолжить',
  'Profile' => 'Профиль',
  'Register' => 'Зарегистрироваться',
  'Registering seller account.' => 'Регистрация аккаунта продавца.',
  'Registration completed.' => 'Регистрация завершена',
  'Registration confirmation' => 'Подтверждение регистрации',
  'Remember me' => 'Запомнить меня',
  'Reminder: {name}' => 'Напоминание: {name}',
  'Reminders' => 'Напоминания',
  'Save' => 'Сохранить',
  'Seller Registration' => 'Регистрация продавца',
  'Service History' => 'История обслуживания',
  'Service History for: ' => 'История обслуживания для:',
  'Set location in your profile' => 'Укажите ваше расположение в профиле',
  'Shop' => 'Магазин',
  'Shop name' => 'Название магазина',
  'Shops' => 'Магазины',
  'Shops near you' => 'Магазины возле вас',
  'Show all' => 'Показать все',
  'Show terms' => 'Показать условия',
  'State' => 'Регион',
  'Suported car brands' => 'Поддерживаемые автомобильные брэнды',
  'Suported part types' => 'Предоставляемые услуги',
  'Terms of use' => 'Условия использования',
  'Thank you!<br />You have been successfully registered on {sitename}' => 'Спасибо!<br />Вы были успешно зарегистрированы на {sitename}',
  'This email is already in use.' => 'Этот email уже занят',
  'Type' => 'Тип',
  'Update' => 'Обновить',
  'Update Shop: ' => 'Изменение магазина',
  'Update car' => 'Редактировать',
  'Update image' => 'Изменить изображение',
  'Updating: ' => 'Редактирование:',
  'User' => 'Пользователь',
  'User Registration' => 'Регистрация пользователя',
  'Value' => 'Цена',
  'View Service History' => 'Показать историю обслуживания',
  'View car' => 'Просмотр автомобиля',
  'View shop: ' => 'Просмотр магазина: ',
  'We don\'t use your private information like location and don\'t share it with third-party persons.<br />By sharing your location you became able to:<ul><li>find stores near you where you can buy parts for your car</li><li>share your experience with others</li><li>get help from users near you</li><li>and moch more...</li></ul>' => 'Мы не используем вашу личную информацию, такую как ваше расположение, и не предоставляем ее третьим лицам.<br />Предоставляя информацию о ващем расположении, вы получаете возможность:<ul><li>искать магазины и СТО в вашем регионе, где вы можете приобрести запчасти и услуги для вашего автомобиля</li><li>делиться опытом и информацией с другими пользователями</li><li>получать помощь от пользователей, находящихся неподалеку</li><li>и многое другое, что сейчас в разработке...</li></ul>',
  'Without premium account you can have only one shop.' => 'Без премиум-подписки вы можете добавить только один магазин.',
  'Without premium account you can have only {num} items attached to your shop.' => 'Без премиум-подписки вы можете проассоциировать свой магазин только с {num} автомобильными брендами и услугами.',
  'Year built' => 'Год производства',
  'Year is not set' => 'Год не указан',
  'You can sell for all brands only with premium account.' => 'Вы можете продавать для всех брендов только с премиум аккаунтом',
  'You didn\'t set your location.' => 'Вы не указали ваше местоположение',
  'Your Mileage' => 'Ваш пробег',
  'Your Period' => 'Ваш период',
  'Your car data has been expired' => 'Ваша машина давно не обновлялась',
  'Your cars' => 'Ваши машины',
  'Your profile has been successfully updated.' => 'Ваш профиль был успешно обновлен.',
  'Your shops' => 'Ваши магазины',
  'days' => 'дней',
  'eXciTer. All rights reserved.' => 'eXciTer. Все права защищены.',
  'km' => 'км',
  'miles' => 'мили',
  '{name} is outdated' => '{name} давно не обновлялось',
);
